a, b=input().split()
x=int(a)
y=int(b)
result_add=int(x+y)
result_sub=int(x-y)
result_mul=int(x*y)
result_div=int(x/y)
result_mod=int(x%y)
print(result_add)
print(result_sub)
print(result_mul)
print(result_div)
print(result_mod)